apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devpunk.fullname" . }}
  labels:
    {{- include "devpunk.labels" . | nindent 4 }}
type: Opaque
data:
  SERVER_PORT: {{ toString .Values.service.port | b64enc }}
{{- range $envKey, $envVal := .Values.env }}
  {{ $envKey | upper }}: {{ $envVal | b64enc }}
{{- end }}
